/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces.filter;

import business.Car;
import business.Fleet;
import java.util.Arrays;
import java.util.TreeSet;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raghavan
 */
public class FilterByManufacturedYear extends javax.swing.JPanel {

    private Fleet fleet;
    private JTable resultsTable;
    /**
     * Creates new form FilterByManufacturer
     */
    public FilterByManufacturedYear() {
        initComponents();
    }

    public FilterByManufacturedYear(Fleet fleet, JTable resultsTable) {
        this.fleet = fleet;
        this.resultsTable = resultsTable;
        
        initComponents();
        populateComboBox();
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        yearListComboBox = new javax.swing.JComboBox<>();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(850, 130));
        setPreferredSize(new java.awt.Dimension(850, 130));

        jLabel1.setText("Manufactured Year");

        yearListComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        yearListComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                yearListComboBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(yearListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(634, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yearListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void populateComboBox() {
        TreeSet<Integer> yearSet = fleet.getYear();
        Integer[] yearList = yearSet.toArray(new Integer[yearSet.size()]);
        String[] yearListString = Arrays.toString(yearList)
                                        .split("[\\[\\]]")[1].split(", ");
        
        yearListComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(yearListString));
    }
    
    private void yearListComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yearListComboBoxItemStateChanged
        Integer filterByYear;
        filterByYear = Integer.parseInt((String) yearListComboBox.getSelectedItem());
        
        DefaultTableModel tableModel = (DefaultTableModel) resultsTable.getModel();
        Object row[] = new Object[tableModel.getColumnCount()];

        tableModel.setRowCount(0);
        for(Car c : fleet.filterByManufacturedYear(filterByYear)) {
            row[0] = c;
            row[1] = c.getManufacturedYear();
            tableModel.addRow(row);
        }
    }//GEN-LAST:event_yearListComboBoxItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> yearListComboBox;
    // End of variables declaration//GEN-END:variables
}
