/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces.filter;

import business.Car;
import business.Fleet;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raghavan
 */
public class FilterBySerialNumberPanel extends javax.swing.JPanel {

    private Fleet fleet;
    private JTable resultsTable;
    private JSplitPane advFilterSplitPane;
    /**
     * Creates new form filterBySerialNumberPanel
     */
    public FilterBySerialNumberPanel() {
        initComponents();
    }

    public FilterBySerialNumberPanel(Fleet fleet, JTable resultsTable, JSplitPane advFilterSplitPane) {
        this.fleet = fleet;
        this.resultsTable = resultsTable;
        this.advFilterSplitPane = advFilterSplitPane;
        initComponents();
        hideErrorLables();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        serialNumberFilterTextField = new javax.swing.JTextField();
        showResultsButton = new javax.swing.JButton();
        serialNumberErrorLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(850, 130));
        setPreferredSize(new java.awt.Dimension(850, 130));

        jLabel1.setText("Serial Number");

        showResultsButton.setText("Show Results");
        showResultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showResultsButtonActionPerformed(evt);
            }
        });

        serialNumberErrorLabel.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        serialNumberErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        serialNumberErrorLabel.setText("Invalid value");

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(serialNumberFilterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 622, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(serialNumberErrorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(showResultsButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(showResultsButton)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serialNumberFilterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serialNumberErrorLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showResultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showResultsButtonActionPerformed
        if(validateForm()) {
            String filterBySerialNumber = serialNumberFilterTextField.getText();
            
            DefaultTableModel tableModel = (DefaultTableModel) resultsTable.getModel();
            Object row[] = new Object[tableModel.getColumnCount()];
            
            tableModel.setRowCount(0);
            Car c = fleet.filterBySerialNumber(filterBySerialNumber);
            row[0] = c;
            row[1] = c.getManufacturer();
            row[2] = c.getModelNumber();
            tableModel.addRow(row);
        } else {
            JOptionPane.showMessageDialog(null, "Invalid values in the form!");
        }
    }//GEN-LAST:event_showResultsButtonActionPerformed

    private void hideErrorLables() {
        serialNumberErrorLabel.setVisible(false);
    }
    
    private boolean validateForm() {
        boolean isValid = true;
        hideErrorLables();
        if("".equals(serialNumberFilterTextField.getText())) {
            isValid = false;
            serialNumberErrorLabel.setVisible(!isValid);
        }
        return isValid;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel serialNumberErrorLabel;
    private javax.swing.JTextField serialNumberFilterTextField;
    private javax.swing.JButton showResultsButton;
    // End of variables declaration//GEN-END:variables
}
