/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import business.Fleet;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author raghavan
 */
public class MainFrame extends javax.swing.JFrame {

    private Fleet fleet;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        File f1, f2;
        BufferedImage image1, image2;
        Image scaledImage1, scaledImage2;
        this.fleet = new Fleet();
        initComponents();
        updateLastUpdatedOn();
        try {
            f1 = new File(System.getProperty("user.dir") + 
                                            "/resources/images/uber_homescreen.jpg");
            f2 = new File(System.getProperty("user.dir") + 
                                            "/resources/images/uber_logo.jpg");
            image1 = ImageIO.read(f1);
            image2 = ImageIO.read(f2);
            scaledImage1 = image1.getScaledInstance(1360, 768, Image.SCALE_FAST);
            scaledImage2 = image2.getScaledInstance(166, 166, Image.SCALE_FAST);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error rendering Picture!");
            return;
        }
        
        imageLabel.setIcon(new ImageIcon(scaledImage1));
        iconLabel.setIcon(new ImageIcon(scaledImage2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainSplitPane = new javax.swing.JSplitPane();
        controlPane = new javax.swing.JPanel();
        createButton = new javax.swing.JButton();
        manageButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lastUpdatedOnLabel = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        viewPanel = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 360));
        setName("UberMainFrame"); // NOI18N
        setResizable(false);

        mainSplitPane.setLastDividerLocation(170);
        mainSplitPane.setMaximumSize(new java.awt.Dimension(1360, 768));
        mainSplitPane.setMinimumSize(new java.awt.Dimension(640, 360));
        mainSplitPane.setPreferredSize(new java.awt.Dimension(1360, 768));

        controlPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        controlPane.setMaximumSize(new java.awt.Dimension(360, 768));
        controlPane.setMinimumSize(new java.awt.Dimension(170, 360));
        controlPane.setPreferredSize(new java.awt.Dimension(360, 768));

        createButton.setText("Create New Car");
        createButton.setMaximumSize(new java.awt.Dimension(150, 50));
        createButton.setMinimumSize(new java.awt.Dimension(150, 50));
        createButton.setPreferredSize(new java.awt.Dimension(150, 50));
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        manageButton.setText("Manage Cars");
        manageButton.setMaximumSize(new java.awt.Dimension(150, 50));
        manageButton.setMinimumSize(new java.awt.Dimension(150, 50));
        manageButton.setPreferredSize(new java.awt.Dimension(150, 50));
        manageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 3, 14)); // NOI18N
        jLabel1.setText("Last Updated On:");

        lastUpdatedOnLabel.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lastUpdatedOnLabel.setText("01/01/1900 00:00:00");

        javax.swing.GroupLayout controlPaneLayout = new javax.swing.GroupLayout(controlPane);
        controlPane.setLayout(controlPaneLayout);
        controlPaneLayout.setHorizontalGroup(
            controlPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPaneLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(manageButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lastUpdatedOnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(iconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        controlPaneLayout.setVerticalGroup(
            controlPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPaneLayout.createSequentialGroup()
                .addComponent(iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 408, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lastUpdatedOnLabel)
                .addContainerGap())
        );

        mainSplitPane.setLeftComponent(controlPane);

        viewPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout viewPanelLayout = new javax.swing.GroupLayout(viewPanel);
        viewPanel.setLayout(viewPanelLayout);
        viewPanelLayout.setHorizontalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE)
        );
        viewPanelLayout.setVerticalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
        );

        mainSplitPane.setRightComponent(viewPanel);

        getContentPane().add(mainSplitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        CreateCarPanel createCarPanel = new CreateCarPanel(lastUpdatedOnLabel, fleet);
        mainSplitPane.setRightComponent(createCarPanel);
    }//GEN-LAST:event_createButtonActionPerformed

    private void manageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageButtonActionPerformed
        ManageCarsPanel manageCarPanel = new ManageCarsPanel(lastUpdatedOnLabel, fleet);
        mainSplitPane.setRightComponent(manageCarPanel);
    }//GEN-LAST:event_manageButtonActionPerformed

    private void updateLastUpdatedOn() {
        DateFormat df = new SimpleDateFormat("MM/dd/yyyy hh:mm:ss a");
        lastUpdatedOnLabel.setText(df.format(fleet.getLastModifiedOn()));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        MainFrame mainFrame = new MainFrame();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mainFrame.setTitle("Uber Car Manager");
                mainFrame.setVisible(true);
            }
        });
        
        /* Add a shutdown hook for backing up the data */
        Runtime.getRuntime().addShutdownHook(new Thread(new Runnable() {
            public void run() {
                try {
                    mainFrame.fleet.backupData();
                } catch (IOException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }, "Shutdown-thread"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlPane;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lastUpdatedOnLabel;
    private javax.swing.JSplitPane mainSplitPane;
    private javax.swing.JButton manageButton;
    private javax.swing.JPanel viewPanel;
    // End of variables declaration//GEN-END:variables
}
