/*
 * Copyright (C) 2018 Raghavan Renganathan <renganathan.raghavan@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ui;

import collections.AirlinesDirectory;
import collections.CustomerDirectory;
import utils.ImageTools;
import java.awt.CardLayout;
import java.awt.Graphics;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import models.Customer;
import services.LoginService;

/**
 * This class renders the Login page
 *
 * @author Raghavan Renganathan <renganathan.raghavan@gmail.com>
 */
public class LoginPage extends javax.swing.JPanel {

    /**
     * JPanel instance for storing the reference to the main JPanel container
     * with Card Layout
     */
    private JPanel pnlContainer;
    
    /**
     * Represents the current user's role (Agent or Customer)
     */
    private String role;
    
    /**
     * Private members which will hold the data regarding Customers, Flights,
     * Airliners and Agents
     */
    private AirlinesDirectory airlinesDir;
    private CustomerDirectory customerDir;

    /**
     * Creates new form LoginPage
     * @param pnlContainer  The root JPanel container with Card Layout
     * @param role          The role of the user (Customer or Agent)
     * @param airlinesDir   The Directory of airlines
     * @param customerDir   The Directory of customers
     */    
    public LoginPage(JPanel pnlContainer, String role, 
            AirlinesDirectory airlinesDir, CustomerDirectory customerDir) {
        this.pnlContainer = pnlContainer;
        this.role = role;
        initComponents();
        if("Agent".equals(role))
            agentSpecificTasks(airlinesDir, customerDir);
        else
            customerSpecificTasks(airlinesDir, customerDir);
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(ImageTools.loadImage("flight-background.png", 1360, 768), 0, 0, null);
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDetails = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        lblRegister = new javax.swing.JLabel();
        lblRegisterLink = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnLoginSignup = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();

        setPreferredSize(new java.awt.Dimension(1360, 768));

        pnlDetails.setBackground(new java.awt.Color(255, 255, 255));
        pnlDetails.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153)));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(153, 153, 153));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Please Log In or Register");

        lblUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(153, 153, 153));
        lblUsername.setText("Username");

        lblPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(153, 153, 153));
        lblPassword.setText("Password");

        lblRegister.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRegister.setText("Not a member? You can register");

        lblRegisterLink.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRegisterLink.setForeground(new java.awt.Color(0, 153, 255));
        lblRegisterLink.setText("here.");
        lblRegisterLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnBack.setBackground(new java.awt.Color(20, 195, 240));
        btnBack.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnBack.setText("< Back");
        btnBack.setToolTipText("Choose role.");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnLoginSignup.setBackground(new java.awt.Color(20, 195, 240));
        btnLoginSignup.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnLoginSignup.setText("Login");
        btnLoginSignup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLoginSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginSignupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDetailsLayout = new javax.swing.GroupLayout(pnlDetails);
        pnlDetails.setLayout(pnlDetailsLayout);
        pnlDetailsLayout.setHorizontalGroup(
            pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetailsLayout.createSequentialGroup()
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDetailsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlDetailsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblRegister)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRegisterLink)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDetailsLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDetailsLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                                .addComponent(btnLoginSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                            .addComponent(txtUsername)
                            .addGroup(pnlDetailsLayout.createSequentialGroup()
                                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPassword)
                                    .addComponent(lblUsername))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtPassword))))
                .addContainerGap())
        );
        pnlDetailsLayout.setVerticalGroup(
            pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetailsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblTitle)
                .addGap(37, 37, 37)
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegister)
                    .addComponent(lblRegisterLink))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoginSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(pnlDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(860, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(pnlDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handler for the click event of Back button
     * @param evt Java ActionEvent object
     */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        pnlContainer.remove(this);
        CardLayout layout = (CardLayout) pnlContainer.getLayout();
        layout.previous(pnlContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * Handler for the click event of Login/SignUp button
     * @param evt Java ActionEvent object
     */
    private void btnLoginSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginSignupActionPerformed
        String username = txtUsername.getText();
        String password = new String(txtPassword.getPassword());
        
        if(username.equals("") || password.equals("")) {
            JOptionPane.showMessageDialog(null,
                    "Please provide username and password");
            return;
        }
        
        if(role == "Agent") {
            if(!LoginService.doAgentLogin(username, password)) {
                JOptionPane.showMessageDialog(null,
                    "Incorrect username or password!");
                return;
            }
            ui.agent.HomePage homePage = new ui.agent.HomePage(airlinesDir, 
                                                                customerDir);
            pnlContainer.add(homePage);
            CardLayout layout = (CardLayout) pnlContainer.getLayout();
            layout.next(pnlContainer);
        } else {
            Customer curr = 
                    LoginService.doCustLogin(username, password, customerDir);
            if(curr == null) {
                JOptionPane.showMessageDialog(null,
                    "Incorrect username or password!");
                return;
            }
            ui.agent.HomePage homePage = new ui.agent.HomePage(airlinesDir, 
                                                                customerDir);
            pnlContainer.add(homePage);
            CardLayout layout = (CardLayout) pnlContainer.getLayout();
            layout.next(pnlContainer);
        }
    }//GEN-LAST:event_btnLoginSignupActionPerformed
    
    /**
     * Method that handles tasks when a customer has landed on this page
     */
    private void customerSpecificTasks(AirlinesDirectory airlinesDir, 
            CustomerDirectory customerDir) {
        this.airlinesDir = airlinesDir;
        this.customerDir = customerDir;
    }
    
    /**
     * Method that handles tasks when an agent has landed on this page
     */
    private void agentSpecificTasks(AirlinesDirectory airlinesDir, 
            CustomerDirectory customerDir) {
        this.customerDir = customerDir;
        this.airlinesDir = airlinesDir;
        lblTitle.setText("Please Log In");
        lblRegister.setVisible(false);
        lblRegisterLink.setVisible(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLoginSignup;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblRegisterLink;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlDetails;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
