/*
 * Copyright (C) 2018 Raghavan Renganathan <renganathan.raghavan@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ui.agent;

import collections.AirlinesDirectory;
import collections.CustomerDirectory;
import utils.ImageTools;

/**
 * This class renders the HomePage when an agent logs in
 *
 * @author Raghavan Renganathan <renganathan.raghavan@gmail.com>
 */
public class HomePage extends javax.swing.JPanel {

    /**
     * Private members which will hold the data regarding Customers, Flights,
     * Airliners and Agents
     */
    private AirlinesDirectory airlinesDir;
    private CustomerDirectory customerDir;
    
    /**
     * Creates new form HomePage
     * @param airlinesDir The Directory of airlines
     * @param customerDir The Directory of customers
     */
    public HomePage(AirlinesDirectory airlinesDir, 
                        CustomerDirectory customerDir) {
        this.airlinesDir = airlinesDir;
        this.customerDir = customerDir;
        initComponents();
        ImageTools.setIcon(lblLogo, "flight-logo.png", 100, 100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpTripType = new javax.swing.ButtonGroup();
        pnlTitle = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        tabPnlMain = new javax.swing.JTabbedPane();
        pnlManage = new javax.swing.JPanel();
        pnlInnerManage = new javax.swing.JPanel();
        lblSubtitle = new javax.swing.JLabel();
        sepFirst = new javax.swing.JSeparator();
        scrollTblCntr = new javax.swing.JScrollPane();
        tblAirlines = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btmCreate = new javax.swing.JButton();
        pnlSearch = new javax.swing.JPanel();
        pnlInnerSearch = new javax.swing.JPanel();
        lblSubtitle1 = new javax.swing.JLabel();
        sepFirst1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txtFrom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtStartDate = new javax.swing.JTextField();
        txtReturnDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        radioSingle = new javax.swing.JRadioButton();
        radioRoundTrip = new javax.swing.JRadioButton();
        btnSearch = new javax.swing.JButton();
        btnListAll = new javax.swing.JButton();
        txtAirlineFilter = new javax.swing.JTextField();
        txtFlightFilter = new javax.swing.JTextField();
        chckBoxAirline = new javax.swing.JCheckBox();
        chckBoxFlight = new javax.swing.JCheckBox();
        btnFilter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFilteredResults = new javax.swing.JTable();
        btnBook = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1360, 768));

        pnlTitle.setPreferredSize(new java.awt.Dimension(1360, 100));

        lblLogo.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setText("The Flight Agency");

        btnLogout.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnLogout.setText("Log Out");

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
            .addGroup(pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTitleLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout)
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTitleLayout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(lblLogo)
                    .addContainerGap(27, Short.MAX_VALUE)))
        );

        pnlManage.setLayout(new java.awt.CardLayout());

        lblSubtitle.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        lblSubtitle.setText("Airlines");

        tblAirlines.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollTblCntr.setViewportView(tblAirlines);

        btnView.setText("View");

        btmCreate.setText("Create");

        javax.swing.GroupLayout pnlInnerManageLayout = new javax.swing.GroupLayout(pnlInnerManage);
        pnlInnerManage.setLayout(pnlInnerManageLayout);
        pnlInnerManageLayout.setHorizontalGroup(
            pnlInnerManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInnerManageLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlInnerManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInnerManageLayout.createSequentialGroup()
                        .addComponent(lblSubtitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sepFirst))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInnerManageLayout.createSequentialGroup()
                        .addGroup(pnlInnerManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scrollTblCntr, javax.swing.GroupLayout.DEFAULT_SIZE, 1315, Short.MAX_VALUE)
                            .addGroup(pnlInnerManageLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(pnlInnerManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btmCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20))))
        );
        pnlInnerManageLayout.setVerticalGroup(
            pnlInnerManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInnerManageLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlInnerManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sepFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubtitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTblCntr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btmCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pnlManage.add(pnlInnerManage, "card2");

        tabPnlMain.addTab("Manage Airliners", pnlManage);

        pnlSearch.setLayout(new java.awt.CardLayout());

        lblSubtitle1.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        lblSubtitle1.setText("Search");

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel1.setText("From");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel2.setText("To");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel3.setText("Start Date");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel4.setText("Return Date");

        btnGrpTripType.add(radioSingle);
        radioSingle.setText("One Way");
        radioSingle.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioSingleItemStateChanged(evt);
            }
        });

        btnGrpTripType.add(radioRoundTrip);
        radioRoundTrip.setText("Round Trip");
        radioRoundTrip.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioRoundTripItemStateChanged(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnSearch.setText("Search Flights");

        btnListAll.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnListAll.setText("List All Flights");

        txtAirlineFilter.setEnabled(false);

        txtFlightFilter.setEnabled(false);

        chckBoxAirline.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        chckBoxAirline.setText("Airline");
        chckBoxAirline.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chckBoxAirlineItemStateChanged(evt);
            }
        });

        chckBoxFlight.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        chckBoxFlight.setText("Flight");
        chckBoxFlight.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chckBoxFlightItemStateChanged(evt);
            }
        });

        btnFilter.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnFilter.setText("Filter Results");
        btnFilter.setEnabled(false);

        tblFilteredResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblFilteredResults);

        btnBook.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnBook.setText("Book Flight");

        javax.swing.GroupLayout pnlInnerSearchLayout = new javax.swing.GroupLayout(pnlInnerSearch);
        pnlInnerSearch.setLayout(pnlInnerSearchLayout);
        pnlInnerSearchLayout.setHorizontalGroup(
            pnlInnerSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInnerSearchLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlInnerSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInnerSearchLayout.createSequentialGroup()
                        .addComponent(lblSubtitle1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sepFirst1))
                    .addGroup(pnlInnerSearchLayout.createSequentialGroup()
                        .addGroup(pnlInnerSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlInnerSearchLayout.createSequentialGroup()
                                .addGroup(pnlInnerSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAirlineFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chckBoxAirline))
                                .addGap(18, 18, 18)
                                .addGroup(pnlInnerSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chckBoxFlight)
                                    .addGroup(pnlInnerSearchLayout.createSequentialGroup()
                                        .addComponent(txtFlightFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnFilter))))
                            .addGroup(pnlInnerSearchLayout.createSequentialGroup()
                                .addGroup(pnlInnerSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(pnlInnerSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(pnlInnerSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addGroup(pnlInnerSearchLayout.createSequentialGroup()
                                        .addComponent(radioRoundTrip)
                                        .addGap(18, 18, 18)
                                        .addComponent(radioSingle)))
                                .addGap(18, 18, 18)
                                .addGroup(pnlInnerSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(84, 84, 84)
                                .addGroup(pnlInnerSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnListAll, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );
        pnlInnerSearchLayout.setVerticalGroup(
            pnlInnerSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInnerSearchLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlInnerSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sepFirst1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubtitle1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInnerSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInnerSearchLayout.createSequentialGroup()
                        .addGroup(pnlInnerSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlInnerSearchLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlInnerSearchLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlInnerSearchLayout.createSequentialGroup()
                                .addGroup(pnlInnerSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlInnerSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlInnerSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioSingle)
                            .addComponent(radioRoundTrip)))
                    .addGroup(pnlInnerSearchLayout.createSequentialGroup()
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnListAll, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(pnlInnerSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chckBoxAirline)
                    .addComponent(chckBoxFlight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInnerSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAirlineFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlInnerSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFlightFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFilter)))
                .addGap(18, 18, 18)
                .addGroup(pnlInnerSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInnerSearchLayout.createSequentialGroup()
                        .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 304, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );

        pnlSearch.add(pnlInnerSearch, "card3");

        tabPnlMain.addTab("Search Flights", pnlSearch);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPnlMain)
            .addComponent(pnlTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(tabPnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void radioRoundTripItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioRoundTripItemStateChanged

    }//GEN-LAST:event_radioRoundTripItemStateChanged

    /**
     * Handler for State Change event for Trip Type Radio Button
     * @param evt Java ActionEvent object
     */
    private void radioSingleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioSingleItemStateChanged
        txtReturnDate.setText("");
        txtReturnDate.setEnabled(false);
    }//GEN-LAST:event_radioSingleItemStateChanged

    /**
     * Handler for State Change event for Airline Filter
     * @param evt Java ActionEvent object
     */
    private void chckBoxAirlineItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chckBoxAirlineItemStateChanged
        txtAirlineFilter.setEnabled(chckBoxAirline.isSelected());
        btnFilter.setEnabled(chckBoxAirline.isSelected() | 
                                chckBoxFlight.isSelected());
    }//GEN-LAST:event_chckBoxAirlineItemStateChanged

    /**
     * Handler for State Change event for Flight Filter
     * @param evt Java ActionEvent object
     */
    private void chckBoxFlightItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chckBoxFlightItemStateChanged
        txtFlightFilter.setEnabled(chckBoxFlight.isSelected());
        btnFilter.setEnabled(chckBoxFlight.isSelected() |
                                chckBoxAirline.isSelected());
    }//GEN-LAST:event_chckBoxFlightItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmCreate;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnFilter;
    private javax.swing.ButtonGroup btnGrpTripType;
    private javax.swing.JButton btnListAll;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnView;
    private javax.swing.JCheckBox chckBoxAirline;
    private javax.swing.JCheckBox chckBoxFlight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblSubtitle1;
    private javax.swing.JPanel pnlInnerManage;
    private javax.swing.JPanel pnlInnerSearch;
    private javax.swing.JPanel pnlManage;
    private javax.swing.JPanel pnlSearch;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JRadioButton radioRoundTrip;
    private javax.swing.JRadioButton radioSingle;
    private javax.swing.JScrollPane scrollTblCntr;
    private javax.swing.JSeparator sepFirst;
    private javax.swing.JSeparator sepFirst1;
    private javax.swing.JTabbedPane tabPnlMain;
    private javax.swing.JTable tblAirlines;
    private javax.swing.JTable tblFilteredResults;
    private javax.swing.JTextField txtAirlineFilter;
    private javax.swing.JTextField txtFlightFilter;
    private javax.swing.JTextField txtFrom;
    private javax.swing.JTextField txtReturnDate;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JTextField txtTo;
    // End of variables declaration//GEN-END:variables
}
